apiVersion: v1
kind: Secret
metadata:
  name: micro-telemetry-secrets
  namespace: student-iglausser
type: Opaque
stringData:
  DB_PASSWORD: telemetry_pass
  MICRO_TELEMETRY_API_KEY: temuco_micro_telemetry_secret_key