apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-go-ingress
  namespace: student-jvaldebenito
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  ingressClassName: nginx

  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-go-svc
                port:
                  number: 3001

          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: backend-go-svc
                port:
                  number: 3001