apiVersion: v1
kind: Secret
metadata:
  name: transporte-db-secrets
  namespace: student-jvaldebenito
type: Opaque
data: # Todo en base64 -> echo -n "algun string" | base64
  DB_PASSWORD: dHJhbnNwb3J0ZV9wYXNz   # Asegurarse de configurar usuario y contraseña
  JWT_SECRET: ZGV2X3NlY3JldF9jYW1iaWFybG9fZW5fcHJvZHVjY2lvbl8xMjM=