apiVersion: v1
kind: Secret
metadata:
  name: micros-secrets
  namespace: student-jvaldebenito
type: Opaque
data: # Todo en base64 -> echo -n "algun string" | base64
  DB_PASSWORD: bWljcm9zX3Bhc3M=   # Asegurarse de configurar usuario y contraseña