apiVersion: v1
kind: Service
metadata:
  name: backend-go-svc
  namespace: student-jvaldebenito
spec:
  type: ClusterIP
  selector:
    app: backend-go
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: http